### ISSUE TITLE
Set the label for the table head i.e th 

### ISSUE THREAD

**Issue by Azezal4** [beta-analytics/sdt#5]
Currently the code need the initialization of the sdt object with select for the selection of a single column.

We need feature as : 
```javascript
let dt = new simpleDatatables.DataTable(`#table-${divId}`, {
                    headers: false,
                    layout: { top: '', bottom: '' },
                    columns : [
                             { 
                                 select: 'Name of Col',
                                 label  : 'Renaming the col'
                  }
        ]
})
```
as shown in code above the headers need to be manually set to false. Since, we are supplying the headers from the backend and are rendering template table. So need for the header is none. 
Therefore, we need to disable it by default.

**Comment by rhoit** [comment]
https://datatables.net/reference/option/columns.title

original datatables has the key as 'title'.
